[build]
  publish = "."  # Your publish directory, change if needed

[[edge_functions]]
  path = "/*"           # Protect all routes
  function = "basic-auth"  # Name of your edge function file (basic-auth.js)
